Dev-roll/thundercard

- pubspec.yaml
> chore: font_awesome_flutterを追加

- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- lib/Account.dart
- lib/List.dart
- lib/Notifications.dart
- lib/Thundercard.dart
- lib/main.dart
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- macos/Podfile
- pubspec.lock
- pubspec.yaml
> feat: ページ遷移の実装、システムテーマの適用

- lib/variable.dart
> feat: カラーパレットの追加、変数管理用ファイルの追加

- lib/Account.dart
- lib/List.dart
- lib/Notifications.dart
- lib/Thundercard.dart
- lib/main.dart
- lib/widgets/card.dart
closes #13
Co-authored-by: Keigo Kato <keigomichi@users.noreply.github.com>
> chore: ファイル名の変更、リファクタリング、widgetの作成

- lib/Thundercard.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
> feat: add qr_flutter and make some samples

- lib/List.dart
- lib/widgets/chat/add_room_page.dart
- lib/widgets/chat/chat_page.dart
- lib/widgets/chat/room_list_page.dart
- lib/widgets/my_qr_code.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> feat: add chat plugin

- lib/Thundercard.dart
- lib/login.dart
- lib/main.dart
- lib/widgets/my_qr_code.dart
> feat: improve qrcode scanner

- lib/main.dart
> fix: corrected a spelling error

- lib/login.dart
> lonin with another account

- lib/api/firebase_auth.dart
- lib/main.dart
> refactor: add a function for getting uid

- lib/Account.dart
close #87
- 各ページにおいてcard_idを利用する際の処理を含んでいる。
- 他のページにおいて同様の処理をする際の処理は統一したいので，改善点がある場合は共有されたい。
> chore: display account info based on uid

- lib/widgets/notification_item_page.dart
> chore: 通知詳細画面で、DateTimeの表示形式を統一

- lib/Thundercard.dart
- lib/widgets/my_card.dart
> chore: pass card_id instead of uid to my_card widget

- lib/List.dart
> chore: wrap futurebuilder and display MyCard widget if is_user is true

- lib/Account.dart
> chore: change visibility of account info

- lib/add_card.dart
- lib/widgets/scan_qr_code.dart
> feat: QRコード読み取りに成功した場合のページ遷移を追加

- lib/account.dart
- lib/auth_gate copy.dart
- lib/auth_gate.dart
- lib/main.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
- サインイン
- 新規登録
- ログアウト
- 登録後のドキュメント生成
- 登録後のプロフィール編集
- 日本語化
> chore: add auth_gate using flutterfire_ui

- lib/auth_gate.dart
- lib/home_page.dart
- lib/main.dart
MyHomePageをHomePageとして別ファイルに切り出し
> chore: create homepage.dart

- lib/account.dart
- lib/account_registration.dart
- lib/auth_gate.dart
- lib/main.dart
> feat: add a page for profile registration

- lib/widgets/card_element.dart
- lib/widgets/my_card.dart
- lib/widgets/my_card_data.dart
> feat: 名刺のデザイン（デザインを決定、色をcardId自動生成）

- lib/account_editor.dart
- lib/account_registration.dart
flutterfire_uiを使用しているsign inおよびregistration画面は後で検討する
> chore: remove focus from textfield when outside clicked

- lib/account.dart
- lib/list.dart
- lib/thundercard.dart
- lib/upload_image_page.dart
> chore: remove all scrollbar widgets

- lib/list.dart
- lib/thundercard.dart
> chore: FABにより表示が隠れないようにする

- lib/widgets/my_card_data.dart
- lib/widgets/open_app.dart
> feat: 名刺のリンク先に遷移できるようにする

- lib/auth_gate.dart
- lib/home_page.dart
> feat: ナビゲーションの各画面に遷移できるようにする

- lib/add_card.dart
- lib/upload_image_page.dart
> chore: List画面に遷移させる

- lib/notifications.dart
close #157
注意: issueの内容が意図していたものと異なる場合はApproveしないように
> chore: replace text 'loading' with progressindicator

- lib/account.dart
- lib/add_card.dart
- lib/widgets/my_cards.dart
> chore: replace text 'loading' with progress indicator

- lib/custom_progress_indicator.dart
CircularProgressIndicatornのサイズを固定
注意: 更なる改善が必要
> chore: improve style of circularprogressindicator

- lib/account.dart
- lib/widgets/card_info.dart
> chore: create a widget to display a list of informations

- lib/card_details.dart
- lib/list.dart
close #178
注意: 動作確認の際は，SNS等のリンクではない箇所をタップすること
> chore: create a new page for display card details when tapped a card in the list

- lib/upload_image_page.dart
> chore: change position of the textfield

- lib/thundercard.dart
- lib/widgets/fullscreen_qr_code.dart
- lib/widgets/my_qr_code.dart
- lib/widgets/scan_qr_code.dart
> feat: heroによる画面遷移

- lib/chat.dart
- pubspec.lock
- pubspec.yaml
> chore: enable file open in chat page

- lib/list.dart
- lib/thundercard.dart
> chore: FABを変更

- lib/account.dart
- lib/account_registration.dart
- lib/add_card.dart
- lib/api/firebase_firestore.dart
- lib/auth_gate.dart
- lib/card_details.dart
- lib/chat.dart
- lib/home_page.dart
- lib/list.dart
- lib/main.dart
- lib/notifications.dart
- lib/thundercard.dart
- lib/upload_image_page.dart
- lib/widgets/card_info.dart
- lib/widgets/extended_card.dart
- lib/widgets/fullscreen_qr_code.dart
- lib/widgets/my_card.dart
- lib/widgets/my_cards.dart
- lib/widgets/my_qr_code.dart
- lib/widgets/normal_card.dart
- lib/widgets/notification_item.dart
- lib/widgets/notification_item_page.dart
- lib/widgets/scan_qr_code.dart
- lib/widgets/switch_card.dart
> refactor: convert to a relative import

- lib/widgets/normal_card.dart
> fix: 表示名の下部が隠れる問題を解決

- lib/api/return_icon_type.dart
> feat: アイコンタイプを返す関数の実装

- lib/api/return_display_id.dart
> feat: IDを返す関数の実装

- lib/account_registration.dart
- lib/constants.dart
> refactor: アイコン取得方法を変更

- lib/account_editor.dart
> fix: リンクのバグを修正

- lib/api/export_to_image.dart
- lib/api/get_application_documents_file.dart
- lib/thundercard.dart
- lib/widgets/scan_qr_code.dart
> feat: thundercardページのボタンを追加

- lib/thundercard.dart
- lib/widgets/open_app.dart
- lib/widgets/scan_qr_code.dart
> chore: ライトテーマの対応

- lib/widgets/notification_item.dart
> feat: 未読カードにドットを表示

- lib/add_card.dart
- lib/thundercard.dart
- lib/upload_image_page.dart
- lib/widgets/open_app.dart
- lib/widgets/scan_qr_code.dart
> chore: snackbarを上部に表示

- lib/add_card.dart
- lib/upload_image_page.dart
> feat: 名刺追加時にスナックバーを表示

- lib/list.dart
> chore: small FABのデザインを変更

- lib/widgets/card_element.dart
- lib/widgets/normal_card.dart
> fix: heightのデフォルト値を変更

- lib/list.dart
> chore: display a message when there is no card

- lib/account.dart
- lib/api/current_brightness.dart
- lib/api/current_brightness_reverse.dart
- lib/api/return_original_color.dart
- lib/auth_gate.dart
- lib/list.dart
- lib/widgets/avatar.dart
- lib/widgets/card_info.dart
- lib/widgets/my_card.dart
- lib/widgets/normal_card.dart
> chore: アカウントアバターをウィジェット化する

- lib/add_card.dart
> style: align buttons in the center

- lib/account.dart
- lib/account_editor.dart
- lib/account_registration.dart
- lib/card_details.dart
- lib/list.dart
- lib/search.dart
- lib/thundercard.dart
- lib/widgets/card_info.dart
- lib/widgets/fullscreen_qr_code.dart
- lib/widgets/notification_item_page.dart
- lib/widgets/scan_qr_code.dart
> chore: バージョンアップ対応

- lib/widgets/notification_item_page.dart
> chore: enable the button to change the read flag

- lib/card_details.dart
> chore: delete edit button

- lib/account_editor.dart
- lib/account_registration.dart
- lib/list.dart
- lib/search.dart
- lib/widgets/notification_item.dart
- lib/widgets/scan_qr_code.dart
> chore: add property behavior into gesturedetector

- lib/chat.dart
> chore: display name at appbar in chat page

- lib/search.dart
> chore: unfocus search window when outside of it clicked

- lib/account_editor.dart
> fix: リンクが増える問題を解決

- lib/thundercard.dart
> chore: 影の色を修正

- lib/widgets/fullscreen_qr_code.dart
- lib/widgets/scan_qr_code.dart
> chore: 戻るボタンのアイコンを変更

- lib/constants.dart
- lib/widgets/my_qr_code.dart
- lib/widgets/open_app.dart
- lib/widgets/scan_qr_code.dart
> feat: qrコード読み取り時の処理を修正

- lib/account_registration.dart
- lib/widgets/my_card.dart
> fix: 存在しないユーザーに対する処理追加

- lib/list.dart
- lib/search.dart
> feat: カード検索における文字数を無制限に

- lib/search.dart
> chore: 検索性能を改善

- lib/card_details.dart
> chore: 画像の表示位置を変更

- lib/account_editor.dart
- lib/account_registration.dart
> chore: アカウント登録画面のデザインを修正

- lib/my_card_details.dart
- lib/widgets/card_element.dart
- lib/widgets/card_info.dart
- lib/widgets/large_card.dart
- lib/widgets/my_card.dart
- lib/widgets/open_app.dart
> chore: large cardのスタイリング

- lib/widgets/normal_card.dart
> chore: normal cardの表示が崩れないようにする

- lib/api/settings/app_theme.dart
- lib/api/theme_storage.dart
> feat: テーマをローカルに保存

- lib/api/settings/app_theme_storage.dart
- lib/api/settings/card_theme_storage.dart
> chore: api/settings/ *theme_storage.dart内のコメントアウトを削除

- lib/widgets/large_card.dart
- lib/widgets/my_card.dart
- lib/widgets/normal_card.dart
- lib/widgets/preview_card.dart
- lib/widgets/small_card.dart
> chore: Thundercardアイコンへの変更

- lib/account_editor.dart
- lib/account_registration.dart
> chore: テキストフィールドの選択可能範囲を拡大

- lib/sign_in.dart
- lib/sign_up.dart
> fix: TextSpanの文字色を設定

- lib/notifications.dart
> fix: 全てのプラットフォームで通知のページを表示

- lib/card_details.dart
> fix: `is_user`カードへの遷移のバグを修正

- README.md
- README_old.md
- Close #478
README を開発者向けの内容に更新 
```
[x] Yes
[ ] No
```
- 変更したい箇所があればマージ前にどうぞ
> docs: README を開発者向けの内容に更新

- lib/account.dart
- lib/add_card.dart
- lib/list.dart
- lib/notifications.dart
- lib/thundercard.dart
- lib/widgets/my_card.dart
> chore: エラーメッセージのデザイン修正

- lib/upload_image_page.dart
- Close #
```
[ ] Yes
[ ] No
```
-
> feat: `upload_image_page.dart` を `version: 2` に移行

- lib/account.dart
- lib/main.dart
> refactor: constの付加

- lib/account.dart
- lib/account_editor.dart
- lib/api/firebase_firestore.dart
- lib/widgets/card_info.dart
- lib/widgets/large_card.dart
- lib/widgets/normal_card.dart
- lib/widgets/small_card.dart
- Close #488
```
[x] Yes
[ ] No
```
-
> chore: 保存処理

- lib/account_editor.dart
- lib/api/settings/name_controller.dart
- Close #494
```
[x] Yes
[ ] No
```
-
> fix: 名前の更新不具合

- lib/account.dart
- lib/account_editor.dart
- lib/auth_gate.dart
- lib/card_details.dart
- lib/chat.dart
- lib/home_page.dart
- lib/list.dart
- lib/notifications.dart
- lib/search.dart
- lib/thundercard.dart
- lib/widgets/card_info.dart
- lib/widgets/error_message.dart
- lib/widgets/fullscreen_qr_code.dart
- lib/widgets/large_card.dart
- lib/widgets/my_card.dart
- lib/widgets/my_cards.dart
- lib/widgets/my_qr_code.dart
- lib/widgets/normal_card.dart
- lib/widgets/notification_item_page.dart
- lib/widgets/scan_qr_code.dart
- lib/widgets/small_card.dart
- lib/widgets/switch_card.dart
- pubspec.lock
- pubspec.yaml
- Close #491
```
[x] Yes
[ ] No
```
-
> fix: CircularProgressIndicatorの表示改善

- lib/api/provider/firebase_firestore.dart
- lib/card_details.dart
- lib/list.dart
- lib/search.dart
- lib/widgets/maintenance.dart
- lib/widgets/my_card.dart
- Close #
```
[x] Yes
[ ] No
```
-
> chore: cardの情報を新しいデータから取得

- lib/account_registration.dart
- lib/thundercard.dart
- lib/upload_image_page.dart
- lib/widgets/my_card.dart
- lib/widgets/open_app.dart
- lib/widgets/positioned_snack_bar.dart
- lib/widgets/scan_qr_code.dart
- Close #489
```
[x] Yes
[ ] No
```
-
> refactor: snack barの部品化

- lib/widgets/my_card.dart
- Close #507
```
[x] Yes
[ ] No
```
-
> fix: 競合の解消

- lib/home_page.dart
- Close #
```
[x] Yes
[ ] No
```
-
> chore: ユーザーの表示を改善

- lib/widgets/card_info.dart
- Close #511
```
[x] Yes
[ ] No
```
-
> fix: Accountの初回表示時エラーの解決

- lib/card_details.dart
- lib/widgets/card_info.dart
- lib/widgets/my_card.dart
- lib/widgets/positioned_snack_bar.dart
- Close #504
```
[x] Yes
[ ] No
```
-
> feat: error, loadingの処理変更

- lib/account.dart
- lib/api/provider/firebase_firestore.dart
- lib/auth_gate.dart
- Close #513
```
[x] Yes
[ ] No
```
-
> fix: ページインデックスの不整合による問題解決

- lib/card_details.dart
- lib/widgets/maintenance.dart
- Close #
```
[x] Yes
[ ] No
```
-
> fix: largecardの表示不具合を修正

- lib/card_details.dart
- lib/widgets/card_img.dart
- Close #
```
[x] Yes
[ ] No
```
-
> fix: largecardを修正

- lib/card_details.dart
- lib/widgets/card_img.dart
- Close #
```
[x] Yes
[ ] No
```
-
> fix: 削除・メッセージのエラー解消

- lib/upload_image_page.dart
- Close #
```
[x] Yes
[ ] No
```
-
> fix: upload imageを修正

- lib/account_editor.dart
- lib/account_registration.dart
- lib/add_card.dart
- lib/upload_image_page.dart
- lib/widgets/maintenance.dart
- Close #
```
[x] Yes
[ ] No
```
-
> chore: registrationを修正

- lib/account_editor.dart
- lib/account_registration.dart
- Close #525
```
[x] Yes
[ ] No
```
-
> feat: 不要なコメントアウトの削除・ボタンアイコンの追加

- lib/account_registration.dart
- lib/add_card.dart
- lib/widgets/my_card.dart
- Close #532
```
[x] Yes
[ ] No
```
-
> fix: カード交換の不具合を修正

- lib/account_editor.dart
- lib/api/provider/firebase_firestore.dart
- lib/search.dart
- Close #527
```
[x] Yes
[ ] No
```
-
> fix: 検索を修正

- lib/widgets/card_info.dart
- lib/widgets/large_card.dart
- Close #526
```
[x] Yes
[ ] No
```
-
> fix: 表示名が見切れる問題を解決

- lib/account.dart
- lib/thundercard.dart
- lib/widgets/scan_qr_code.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- pubspec.lock
- Close #
```
[x] Yes
[ ] No
```
-
> chore: buildの試行錯誤

- lib/account.dart
- lib/thundercard.dart
- lib/widgets/scan_qr_code.dart
- pubspec.lock
- Close #542
```
[x] Yes
[ ] No
```
-
> refactor: リファクタリング

- lib/widgets/positioned_snack_bar.dart
- Close #309
```
[x] Yes
[ ] No
```
-
> feat: スナックバーのデザイン変更

- lib/account.dart
- lib/link_auth.dart
- Close #492
```
[x] Yes
[ ] No
```
-
> refactor: async gapの問題を解決

- lib/account_editor.dart
- lib/account_registration.dart
- Close #517
```
[x] Yes
[ ] No
```
-
> feat: リンク追加時の自動スクロール機能追加

- lib/account.dart
- lib/list.dart
- lib/widgets/card_info.dart
- Close #535
```
[x] Yes
[ ] No
```
-
> feat: Navigation Barの色を設定

- lib/constants.dart
- lib/home_page.dart
- lib/share_app.dart
- Close #519
```
[x] Yes
[ ] No
```
-
> feat: アプリの共有機能追加

- lib/share_app.dart
- Close #551
```
[x] Yes
[ ] No
```
-
> feat: 「Thundercard をシェア」ページの修正

- lib/home_page.dart
- lib/widgets/md/authors.dart
- Close #550
```
[x] Yes
[ ] No
```
-
> chore: Drawerの項目削減

- lib/cards/providers/current_card_id_provider.dart
- lib/home_page.dart
- Close #560
```
[x] Yes
[ ] No
```
-
> feat: currentCardId を全体で使えるようにする

- lib/add_card.dart
- lib/home_page.dart
- lib/thundercard.dart
- lib/widgets/my_card.dart
- Close #249
```
[x] Yes
[ ] No
```
-
> feat: dynamic links

- lib/widgets/my_card.dart
- Close #565
```
[x] Yes
[ ] No
```
-
> fix: 交換の不具合解消

- lib/account.dart
- lib/account_editor.dart
- lib/account_registration.dart
- lib/add_card.dart
- lib/api/setSystemChrome.dart
- lib/auth_gate.dart
- lib/card_details.dart
- lib/exchange_card.dart
- lib/home_page.dart
- lib/list.dart
- lib/main.dart
- lib/notifications.dart
- lib/thundercard.dart
- lib/upload_image_page.dart
- lib/widgets/card_info.dart
- lib/widgets/dialog_util.dart
- lib/widgets/fullscreen_qr_code.dart
- lib/widgets/input_link.dart
- lib/widgets/md/about_app.dart
- lib/widgets/my_card.dart
- lib/widgets/notification_item_page.dart
- lib/widgets/open_app.dart
- lib/widgets/scan_qr_code.dart
- Close #556
```
[x] Yes
[ ] No
```
-
> feat: 軽微なデザイン修正

- lib/add_card.dart
- lib/home_page.dart
- lib/notifications.dart
- lib/widgets/input_link.dart
- lib/widgets/my_card.dart
- lib/widgets/notification_item.dart
- lib/widgets/notification_item_page.dart
- lib/widgets/scan_qr_code.dart
- Close #568
```
[x] Yes
[ ] No
```
-
> chore: カード交換を改善

- pubspec.lock
- pubspec.yaml
- Close #571
```
[x] Yes
[ ] No
```
-
> fix: パッケージをダウングレード

- lib/card_details.dart
- lib/widgets/card_img.dart
- lib/widgets/image_with_url.dart
- lib/widgets/preview_img.dart
- Close #557
```
[x] Yes
[ ] No
```
-
> feat: 画像をダブルタップで拡大・縮小可能に

- lib/cards/providers/exchanged_cards_provider.dart
- lib/cards/providers/firestore_service_provider.dart
- lib/cards/services/firestore_service.dart
- lib/cards/views/pages/cards_list_page.dart
- lib/cards/views/widgets/cards_list.dart
- lib/cards/views/widgets/cards_list_floating_action_button.dart
- lib/cards/views/widgets/search.dart
- lib/cards/views/widgets/search_window.dart
- lib/home_page.dart
- lib/list.dart
- Close #546
```
[x] Yes
[ ] No
```
-
> perf: `exchangedCards` 取得を StreamProvider で書き換え

- lib/api/input_data_processor.dart
- lib/widgets/scan_qr_code.dart
- pubspec.lock
- pubspec.yaml
- Close #574
```
[x] Yes
[ ] No
```
-
> feat: 画像を選択してQRコード読み取り

- lib/views/pages/add_card.dart
- Close #584
```
[x] Yes
[ ] No
```
-
> fix: 交換の文言および`my`/`another`の修正

- lib/views/pages/add_card.dart
- Close #587
```
[x] Yes
[ ] No
```
-
> fix: roomが2つ作成される問題を解決

- lib/views/pages/account_editor.dart
- Close #593
```
[x] Yes
[ ] No
```
-
> fix: ページ遷移のタイミングを修正

- lib/providers/firebase_firestore.dart
- lib/views/pages/account.dart
- lib/views/pages/auth_gate.dart
- lib/views/pages/cards_list_page.dart
- lib/views/pages/home_page.dart
- lib/views/pages/notifications.dart
- lib/views/pages/sign_in.dart
- lib/views/pages/sign_up.dart
- lib/views/pages/thundercard.dart
- lib/views/widgets/scan_qr_code.dart
- Close #597
```
[x] Yes
[ ] No
```
-
> perf: ページ遷移を高速化

- lib/views/pages/home_page.dart
- Close #599
```
[x] Yes
[ ] No
```
-
> perf: 爆速ローディング

- lib/views/pages/exchange_card.dart
- lib/views/pages/thundercard.dart
- lib/views/widgets/cards_list_floating_action_button.dart
- lib/views/widgets/my_qr_code.dart
- lib/views/widgets/scan_qr_code.dart
- pubspec.lock
- Close #604
```
[x] Yes
[ ] No
```
-
> fix: カード交換画面でIDが存在しない問題を修正

- lib/utils/constants.dart
- lib/utils/input_data_processor.dart
- lib/utils/launch_url.dart
- lib/utils/resolve_short_link.dart
- lib/views/pages/share_app.dart
- lib/views/widgets/input_link.dart
- lib/views/widgets/my_qr_code.dart
- lib/views/widgets/scan_qr_code.dart
- pubspec.lock
- pubspec.yaml
- Close #606
```
[x] Yes
[ ] No
```
-
> feat: QRコードのdynamic links対応

- lib/views/pages/sign_in.dart
- lib/views/pages/sign_up.dart
- Close #609
```
[x] Yes
[ ] No
```
-
> fix: google signinで警告を解消

- lib/views/pages/home_page.dart
- lib/views/widgets/avatar.dart
- lib/views/widgets/card_info.dart
- lib/views/widgets/input_link.dart
- lib/views/widgets/normal_card.dart
- lib/views/widgets/small_card.dart
- Close #122
```
[ ] Yes
[x] No
```
-
> feat: currentUserのアバターを表示

- lib/views/pages/card_details.dart
- lib/views/widgets/notification_item_page.dart
- Close #614
```
[x] Yes
[ ] No
```
-
> feat: 3点ボタンの色を変更

- lib/views/widgets/input_link.dart
- Close #615
```
[x] Yes
[ ] No
```
-
> feat: shorturlからcardidを取得

- lib/main.dart
- Close #626
```
[x] Yes
[ ] No
```
-
> fix: ColorScheme を dynamic color に合わせる

- lib/views/pages/thundercard.dart
- Close #630
```
[x] Yes
[ ] No
```
-
> feat: ホームに通知を表示

- lib/providers/firebase_firestore.dart
- lib/providers/notifications_count_provider.dart
- lib/services/firestore_service.dart
- lib/views/pages/home_page.dart
- lib/views/pages/notifications.dart
- Close #
```
[x] Yes
[ ] No
```
-
> feat: badgeを追加

- lib/views/pages/account.dart
- lib/views/widgets/available_auth.dart
- Close #632
```
[x] Yes
[ ] No
```
-
> feat: 連携済みの認証方法を表示

- lib/views/widgets/cards_list.dart
- Close #639
```
[x] Yes
[ ] No
```
-
> feat: カードを新しい順に表示する

- ios/Podfile.lock
- lib/main.dart
- macos/Podfile.lock
- Close #642
```
[x] Yes
[ ] No
```
-
> fix: テーマを修正

- lib/utils/create_theme.dart
- Close #645
```
[x] Yes
[ ] No
```
-
> fix: webフォントを表示させる

- analysis_options.yaml
- Close #650
```
[x] Yes
[ ] No
```
- https://dart.dev/tools/linter-rules
> chore: introduce flutter_lints

- .github/workflows/label-approved-pull-requests.yml
- Close #
```
[x] Yes
[ ] No
```
-
> ci: add label when approved action

- lib/app.dart
- lib/main.dart
- Close #
- `MyApp` クラスを `app.dart` に切り出した。
- `MyApp` を `ThundercardApp` にrename。
- その他、lintエラー修正等。
```
[x] Yes
[ ] No
```
-
> refactor: refactor main function

- .gitignore
- .idea/dictionaries/thundercardDictionary.xml
- Close #
- Android Studioでスペルに関するwarningが出ないようにプロジェクトに辞書を作成
```
[x] Yes
[ ] No
```
-
> chore: add a dictionary for ide

- .fvm/fvm_config.json
- Close #657
```
[x] Yes
[ ] No
```
-
> chore: fvm use stable

- lib/ui/screen/link_auth.dart
- lib/ui/screen/sign_in.dart
- lib/ui/screen/sign_up.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- Close #686
```
[x] Yes
[ ] No
```
- https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/doc/providers/oauth.md
> feat: replace flutterfire_ui with firebase_ui_auth

- lib/providers/firebase_firestore.dart
- lib/ui/component/my_card.dart
- lib/ui/component/notification_item.dart
- lib/ui/component/notification_item_page.dart
- lib/ui/component/scan_qr_code.dart
- lib/ui/screen/account.dart
- lib/ui/screen/account_editor.dart
- lib/ui/screen/add_card.dart
- lib/ui/screen/card_details.dart
- lib/ui/screen/home_page.dart
- lib/ui/screen/link_auth.dart
- lib/ui/screen/notifications.dart
- lib/ui/screen/sign_in.dart
- lib/ui/screen/sign_up.dart
- lib/ui/screen/thundercard.dart
- lib/ui/screen/upload_image_page.dart
- lib/utils/input_data_processor.dart
- pubspec.lock
- pubspec.yaml
- Close #
Loggerを導入。
```
[x] Yes
[ ] No
```
- https://pub.dev/packages/logger
- 今後、ログ出力にはloggerのメソッドを使う。
> chore: introduce logger

- .gitignore
- Close #
```
[x] Yes
[ ] No
```
-
> chore: add flutter_sdk in gitignore

- README.md
- README_old.md
- lib/ui/component/md/authors.dart
- Close #695
- `notchcoder` を `chnotchy` に変更
```
[x] Yes
[ ] No
```
-
> docs: ユーザー名の変更

- lib/ui/component/my_cards.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- Close #692
```
[x] Yes
[ ] No
```
-
> feat: アイコン画像をキャッシュ

- lib/ui/component/my_card.dart
- Close #698
```
[x] Yes
[ ] No
```
-
> perf: card情報の取得を修正

- .github/workflows/openai-pr-reviewer.yml
- Close #
```
[ ] Yes
[ ] No
```
- https://github.com/coderabbitai/openai-pr-reviewer
New Feature: Added GitHub Actions workflow file for code review using the OpenAI ChatGPT model. The workflow is triggered on pull requests and pull request review comments, and it runs the review job using the `fluxninja/openai-pr-reviewer` action.
> "Code review made easy,
> With OpenAI's power so breezy.
> Workflow triggers on PRs,
> And comments, no stress or mess.
> Reviewing code with utmost care,
> Making improvements everywhere!"
> ci: add openai-pr-reviewer
